# fly.toml app configuration file generated for img-optimizer-fragrant-cloud-4712 on 2024-05-13T16:54:41+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'img-optimizer'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = "shared"
  cpus = 8
  memory = "8gb"
